name: Monthly issue metrics
on:
  workflow_dispatch:
  schedule:
    - cron: '20 22 1 * *'

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    steps:
    - name: Get dates for last month
      shell: bash
      run: |
        # Set the first day to May 1
        first_day="2024-03-01" # You might need to adjust the year accordingly
          
        # Set the last day to May 4
        last_day="2024-03-07" # Again, ensure the year is correct for your needs
        
        # Echo the date range
        echo "$first_day..$last_day"

        echo "hello there"
        
        # Set an environment variable with the date range for use in GitHub Actions
        echo "date_range=$first_day..$last_day" >> "$GITHUB_ENV"

    - name: Run issue-metrics tool
      uses: github/issue-metrics@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:lawang24/issue-metrics is:pr is:closed NOT add in:title'

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v5
      with:
        title: Monthly issue metrics report
        token: ${{ secrets.GITHUB_TOKEN }}
        content-filepath: ./issue_metrics.md