name: test_github
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  notifySlack:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # https://api.slack.com/block-kit
      - name: Send Slack notification
        shell: bash
        run: |
          # multiline output format
          {
          echo 'final_summary<<EOF'
          echo "${{github.event.pull_request.body}}"
          echo EOF
          } >> "$GITHUB_ENV"

      - name: Test Empty Body
        if: final_summary
        run: |
         echo "This will not run"
      
      - name: Test full Body
        if: final_summary
        run: |
          echo "This will run"
          echo $final_summary
      
          
