name: test_github
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

# for security reasons? supposed to keep body as env. var
env: 
  FINAL_SUMMARY: ${{github.event.pull_request.body}}

jobs:
  notifySlack:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Test pos case Body
        if: env.FINAL_SUMMARY
        run: |
         echo "This willasdfasdfjklasd fj run"
          {
          echo 'FINAL_SUMMARY<<EOF'
          echo "hello!"
          echo EOF
          } >> "$GITHUB_ENV"
      
      - name: Test null case Body
        if: ${{!env.FINAL_SUMMARY}}
        run: |
          echo "This shouldn't runrun"
          echo $FINAL_SUMMARY
          
      - name: Test rewrite
        run: echo $FINAL_SUMMARY
        
          
      
          
