name: test_github
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  notifySlack:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # https://api.slack.com/block-kit
      - name: Send Slack notification
        env:
          breaking_label: ${{contains(github.event.pull_request.labels.*.name, 'breaking')}}
          payload: ${{github.event.pull_request.body}}
          
        shell: bash
        run: |
          echo "$payload"
          echo "generating slack message"
          if [ "$breaking_label" = true ] ; then
              echo "hello it works"
          else
              echo "woops"
          fi
          
