name: test_github
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

# for security reasons? supposed to keep body as env. var
env: 
  FINAL_SUMMARY: ${{github.event.pull_request.body}}

jobs:
  notifySlack:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Test pos case Body
        if: env.FINAL_SUMMARY
        run: |
         echo "This willasdfasdfjklasd fj run"
      
      - name: Test null case Body
        if: ${{!env.FINAL_SUMMARY}}
        run: |
          echo "This will run"
          echo $final_summary
      
          
